build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-nodejs:18"
  amd64: "ghcr.io/home-assistant/amd64-base-nodejs:18"
  armhf: "ghcr.io/home-assistant/armhf-base-nodejs:18"
  armv7: "ghcr.io/home-assistant/armv7-base-nodejs:18"
  i386: "ghcr.io/home-assistant/i386-base-nodejs:18"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Octo MQTT"
  org.opencontainers.image.description: "A Home Assistant add-on to enable controlling Octo actuators star version 2."
  org.opencontainers.image.source: "https://github.com/bramboe/octo-mqtt"
  org.opencontainers.image.licenses: "MIT" 