build_from:
  aarch64: ghcr.io/hassio-addons/base:14.3.3
  amd64: ghcr.io/hassio-addons/base:14.3.3
  armhf: ghcr.io/hassio-addons/base:14.3.3
  armv7: ghcr.io/hassio-addons/base:14.3.3
  i386: ghcr.io/hassio-addons/base:14.3.3

labels:
  org.opencontainers.image.title: "Octo Integration via MQTT"
  org.opencontainers.image.description: "Home Assistant Community Add-on for Octo actuators star version 2"
  org.opencontainers.image.source: "https://github.com/bramboe/octo-mqtt"
  org.opencontainers.image.licenses: "MIT" 