name: "Octo MQTT"
version: "1.2.8"
slug: "octo-mqtt"
description: "A Home Assistant add-on to enable controlling Octo actuators star version 2."
url: "https://github.com/bramboe/octo-mqtt.git"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: application
boot: auto
map:
  - share:rw
services:
  - mqtt:need
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: Web interface
hassio_api: true
hassio_role: default
auth_api: true
codenotary: "bramboe@gmail.com"
webui: http://[HOST]:[PORT:8099]
options:
  mqtt_host: "<auto_detect>"
  mqtt_port: "<auto_detect>"
  mqtt_user: "<auto_detect>"
  mqtt_password: "<auto_detect>"
  bleProxies:
    - host: "192.168.1.100"
      port: 6053
      password: ""
      encryptionKey: null
      expectedServerName: null
  target_mac:
    - "AA:BB:CC:DD:EE:FF"
  scan_duration: 30000
  scan_interval: 5000
schema:
  mqtt_host: str?
  mqtt_port: str?
  mqtt_user: str?
  mqtt_password: str?
  bleProxies:
    - host: str
      port: port?
      password: password?
      encryptionKey: match(^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)$)?
      expectedServerName: str?
  target_mac:
    - match(^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$)?
  scan_duration: int(1000,60000)?
  scan_interval: int(1000,30000)? 