name: "Octo MQTT"
version: "1.2.6"
slug: "octo-mqtt"
description: "A Home Assistant add-on to enable controlling Octo actuators star version 2."
url: "https://github.com/bramboe/octo-mqtt.git"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: application
boot: auto
map:
  - share:rw
services:
  - mqtt:need
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: Web interface
hassio_api: true
hassio_role: default
webui: http://[HOST]:[PORT:8099]
options:
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  log_level: "info"
  bleProxies:
    - host: "192.168.2.102"
      port: 6053
  octoDevices:
    - name: "f6:21:dd:dd:6f:19"
      friendlyName: "RC2 Bed"
      pin: "1987"
schema:
  mqtt_host: str
  mqtt_port: port
  mqtt_username: str
  mqtt_password: password
  log_level: list(trace|debug|info|notice|warning|error|fatal)
  bleProxies: list(dict)
  octoDevices: list(dict) 