name: "Octo MQTT"
version: "1.2.8"
slug: "octo-mqtt"
description: "A Home Assistant add-on to enable controlling Octo actuators star version 2."
url: "https://github.com/bramboe/octo-mqtt.git"
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
init: false
startup: application
boot: auto
map:
  - share:rw
services:
  - mqtt:need
ports:
  8099/tcp: 8099
ports_description:
  8099/tcp: Web interface
hassio_api: true
hassio_role: default
webui: http://[HOST]:[PORT:8099]
ingress: true
ingress_port: 8099
panel_icon: mdi:bed
panel_title: "Octo MQTT"
auth_api: true
protection: true
privileged: []
apparmor: true
options:
  mqtt_host: "<auto_detect>"
  mqtt_port: "<auto_detect>"
  mqtt_user: "<auto_detect>"
  mqtt_password: "<auto_detect>"
  bleProxies:
    - host: "192.168.1.109"
      port: 6053
      password: ""
  octoDevices:
    - mac: "f6:21:dd:dd:6f:19"
      friendlyName: "RC2 Bed"
      pin: "1987"
  # Enhanced BLE filtering options
  target_mac: "f6:21:dd:dd:6f:19"
  target_pin: "1987"
  enable_mac_filtering: true
  enable_pin_filtering: true
  scan_duration: 30000
  scan_interval: 5000
  target_device_name: "RC2 Bed"
  ble_scan_duration: 30000
  ble_scan_interval: 100
  ble_scan_window: 50
  ble_scan_active: true
schema:
  mqtt_host: str?
  mqtt_port: port?
  mqtt_user: str?
  mqtt_password: password?
  bleProxies:
    - host: str
      port: port?
      password: password?
      encryptionKey: match(^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)$)?
      expectedServerName: str?
  octoDevices:
    - mac: match(^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$)
      friendlyName: str
      pin: str?
  # Enhanced BLE filtering schema
  target_mac: match(^([0-9A-Fa-f]{2}[:-]){5}([0-9A-Fa-f]{2})$)?
  target_pin: match(^\d{4}$)?
  enable_mac_filtering: bool?
  enable_pin_filtering: bool?
  scan_duration: int(1000,60000)?
  scan_interval: int(1000,30000)?
  target_device_name: str?
  ble_scan_duration: int(10000,60000)?
  ble_scan_interval: int(50,200)?
  ble_scan_window: int(25,100)?
  ble_scan_active: bool? 